# Optional deep-learning track for hsbg-coach.
#
# The core `hsbg_coach` package is intentionally stdlib-only. This ml/ track adds
# a deep-learning dependency (PyTorch) for models that learn from data — starting
# with a combat-evaluation network trained on data generated by the combat sim.
# Install with:  pip install -r requirements-ml.txt
#
# Training is meant for a real machine (CPU is fine for this small net; a GPU
# helps once models grow). Nothing here is needed to run the heuristic advisor.
