"""Phase 3U — allocation-rule scientific-validity audit (measurement design only).

Phase 3T localizes 100% of the paired T5/T6 first synth divergence to the
Phase 2S paint/repaint checkpoint, while the Phase 2S contract itself defines
the synthetic quantity as a conserved player/board pool. Therefore 3U does
NOT test "sticky vs repaint" as competing simulator implementations. It asks
the narrower question: when that conserved board pool must become body-level
combat stats, is the current recruit-raw-proportional allocation scientifically
identified by evidence independent of the candidate simulator?

This file preregisters the comparison before any implementation experiment.
It changes no simulator behavior and consumes no new seeds. The reserved
confirmation band 11500–11699 remains untouched. Existing consumed DEV
14200–14699 may be reused only for diagnostics and estimator development;
it may not itself establish external validity for an allocation rule.
"""

from __future__ import annotations

from typing import Dict, Iterable, Mapping, Optional

METHODOLOGY_VERSION = "3u_v1"
REUSED_DEV_LO = 14200
REUSED_DEV_HI = 14699
CONFIRM_LO = 11500
CONFIRM_HI = 11699
FROZEN_ALPHA = 0.5

CANDIDATE_RULES = (
    "recruit_raw_proportional",  # current 2S paint rule
    "equal_per_body",
    "pre_change_share_carry",   # diagnostic comparator, not sticky-pool semantics
)

# Endogenous simulator outcomes are deliberately excluded as a rule-selection
# target: they are downstream of the very body allocation being compared.
DISALLOWED_SELECTION_TARGETS = (
    "mean_game_length",
    "placement",
    "macro_fidelity_gate",
    "simulated_survival_under_candidate_rule",
    "simulated_damage_under_candidate_rule",
)

# A scientific implementation candidate requires a body-level or otherwise
# allocation-sensitive reference that was not generated by the candidate
# simulator. Aggregate board totals can verify conservation but cannot identify
# how a fixed total should be distributed among bodies.
VALID_REFERENCE_KINDS = (
    "external_body_level_combat_stats",
    "external_body_level_survival_or_damage",
    "held_out_real_game_body_level_trace",
)

CONSERVATION_IDENTITY = (
    "for every snapshot and candidate rule: sum(body synthetic allocation) "
    "equals the same rounded conserved abstract board pool"
)

NO_SELECTION_WITHOUT_REFERENCE = (
    "do not choose or implement an allocation rule unless an independent, "
    "allocation-sensitive reference distinguishes candidates"
)


def assert_no_reserved_confirmation_use(seed: int, lobbies: int) -> None:
    """Reject any range overlapping reserved confirmation seeds 11500–11699."""
    lo = int(seed)
    hi = lo + int(lobbies) - 1
    if lo <= CONFIRM_HI and hi >= CONFIRM_LO:
        raise ValueError(
            f"Phase 3U range {lo}–{hi} overlaps reserved confirmation "
            f"{CONFIRM_LO}–{CONFIRM_HI}"
        )


def assert_reused_dev_only(seed: int, lobbies: int) -> None:
    """Offline 3U diagnostics may only reuse the already-consumed DEV band."""
    assert_no_reserved_confirmation_use(seed, lobbies)
    lo = int(seed)
    hi = lo + int(lobbies) - 1
    if lo < REUSED_DEV_LO or hi > REUSED_DEV_HI:
        raise ValueError(
            f"Phase 3U diagnostic range must stay within reused DEV "
            f"{REUSED_DEV_LO}–{REUSED_DEV_HI}, got {lo}–{hi}"
        )


def reference_is_independent(reference: Optional[Mapping]) -> bool:
    """Return True only for an allocation-sensitive, non-simulator reference."""
    if not reference:
        return False
    kind = reference.get("kind")
    generated_by = reference.get("generated_by")
    allocation_sensitive = bool(reference.get("allocation_sensitive"))
    return (
        kind in VALID_REFERENCE_KINDS
        and generated_by not in {"replay_simulator", "candidate_rule"}
        and allocation_sensitive
    )


def evaluate_phase_3u_design(
    *,
    candidate_scores: Optional[Mapping[str, float]] = None,
    reference: Optional[Mapping] = None,
    conservation_passed: bool = False,
    disallowed_targets_used: Iterable[str] = (),
) -> Dict:
    """Apply the preregistered scientific-validity gate.

    ``candidate_scores`` are meaningful only when ``reference_is_independent``
    is true. Lower scores are assumed better, but this function intentionally
    does not set an effect-size threshold until a concrete external observable
    and its noise model exist.
    """
    used = sorted(set(disallowed_targets_used) & set(DISALLOWED_SELECTION_TARGETS))
    independent = reference_is_independent(reference)
    scores = dict(candidate_scores or {})
    candidates_complete = all(name in scores for name in CANDIDATE_RULES)

    if used:
        route = "invalid_macro_or_endogenous_selection"
    elif not conservation_passed:
        route = "hold_conservation_not_proven"
    elif not independent:
        route = "hold_allocation_underidentified"
    elif not candidates_complete:
        route = "hold_candidate_comparison_incomplete"
    else:
        route = "reference_available_define_effect_threshold_before_selection"

    return {
        "methodology_version": METHODOLOGY_VERSION,
        "route": route,
        "candidate_rules": list(CANDIDATE_RULES),
        "reference_independent": independent,
        "conservation_passed": bool(conservation_passed),
        "candidate_scores_complete": candidates_complete,
        "disallowed_targets_used": used,
        "no_behavior_change": True,
        "no_macro_gate_tuning": True,
        "no_alpha_retune": True,
        "frozen_alpha": FROZEN_ALPHA,
        "confirm_seeds_reserved": f"{CONFIRM_LO}–{CONFIRM_HI}",
        "reused_dev_only": f"{REUSED_DEV_LO}–{REUSED_DEV_HI}",
        "selection_requires_independent_reference": True,
    }
